### ISSUE TITLE
url option broken

### ISSUE THREAD

**Issue by bartocc** [ember-cli-deploy/ember-cli-deploy-redis#33]
I've specified the 'url' key in my redis config object, but it does not seem to be taken in to account and deploy tries to use default host and port.

Using ember-cli-deploy@5.0.0-beta.2

works find if I configure 'host', 'port' and 'password' instead

**Comment by achambers** [comment]
Hi @bartocc . Could you please post the redis url string you are using?

**Comment by bartocc** [comment]
hi @achambers 

here it is with some credentials modifications for security reasons

`redis://h:q86b1nrf2qa75f2eht3554z81q0@ec2-54-217-234-142.eu-west-1.compute.amazonaws.com:15479`

**Comment by achambers** [comment]
@bartocc Okie doke. You need to change your url to this: `redis://:q86b1nrf2qa75f2eht3554z81q0@ec2-54-217-234-142.eu-west-1.compute.amazonaws.com:15479`

The reason is that the `h` is a placeholder for the username. But redis doesn't really use the concept of a username. Give the url above a try and let me know how it goes.

**Comment by bartocc** [comment]
THx @achambers, worked great.

I think ember-cli-deploy-redis should handle URLs with the username placeholder though. I suppose other users will face the same issue one day or another.

For the record, I copied this URL from Heroku Redis dashboard and it works without any modification with the redis gem for example.

**Comment by achambers** [comment]
Yep, we are going to make sure our 0.5.0 plugins handle this. Out of interest, which version of ember-cli-deploy are you using?

**Comment by bartocc** [comment]
using ember-cli-deploy@5.0.0-beta.2 @achambers
