### ISSUE TITLE
Handle heroku redis urls smartly

### ISSUE THREAD

**Issue by achambers** [ember-cli-deploy/ember-cli-deploy-redis#36]
Heroku redis addon url's generally have a placeholder for the username, ie

```
redis://x:345932ywwe659weotwy@some-host:12345
```

That `x` in that url is pointless and breaks the redis package we use.  The required url is:

```
redis://:345932ywwe659weotwy@some-host:12345
```

We should make this plugin handle the url if it includes the username placeholder.

**Comment by jeffreybiles** [comment]
Thanks, this issue was helpful in resolving this problem in my app.

Something to note for future viewers: it's not always an `x`.  Mine was an `h`.

**Comment by acorncom** [comment]
Just hit this myself ;-)  Is the package that we're using at fault or the version of the package that we're using?  From what I'm seeing, it's `v0.12.1` is about two years old, would we want to upgrade that?

If not, I may be able to send in a PR for the above issue ...

**Comment by lukemelia** [comment]
@acorncom Not sure whether the package addresses this in newer versions. We're open to PR using either approach.
