### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by YoranBrondsema** [ember-cli-deploy/ember-cli-deploy-redis#55]
Hi,

From the description of the plugin, `This plugin uploads a file, presumably index.html, to a specified Redis store.`, it seems that uploading multiple files is not supported. In my use-case, besides an `index.html`, I would also like to upload a `assets/print.css` to Redis. Will such a use-case ever be supported by this plugin? 

Thank you,

Yoran

**Comment by achambers** [comment]
Hi. The description you mention is the default. You can customise the file(s) uploaded by setting the `filePattern` property -> https://github.com/ember-cli-deploy/ember-cli-deploy-redis/blob/master/README.md#filepattern

I'm going to close this issue now. If you feel it doesn't answer your question, feel free to reopen

**Comment by YoranBrondsema** [comment]
Thanks for your quick reply. I see, is there any documentation on the format expected by the `filePattern` property?

Also, in the case that it successfully uploads the two files to Redis, what happens with `keyPrefix`? Right now its default is `context.project.name() + ':index'` but in my case I would like to make it dependent on the file name. Is there any way to do that?

**Comment by lukemelia** [comment]
I don't think your feedback is correct @achambers. Even though the plugin supports `filePattern` for matching a file, it expects to match a single path, which is read and then uploaded.

@YoranBrondsema I am open to this plugin evolving to support the case you described, but it's not a priority for me. An alternative is that you can take advantage of ember-cli-deploy's "alias" feature (see ember-cli-deploy docs) to have two instances of the redis plugin run, each with its own configuration.

**Comment by YoranBrondsema** [comment]
@lukemelia The alias feature looks exactly what I need, thanks! Then it makes sense that uploading multiple files in this plugin is not a priority.

**Comment by achambers** [comment]
@lukemelia - yup, you're right. That'll teach me for busting out PR comments on my phone while on holiday. Sorry about the bum steer
