### ISSUE TITLE
Connecting manually via redis-cli works but ember-cli-deploy-redis gets a "connect ETIMEDOUT" error

### ISSUE THREAD

**Issue by BillBrower** [ember-cli-deploy/ember-cli-deploy-redis#62]
Redis is running on a server that is not publicly accessible (it's in a private subnet) so I'm using ssh tunnel to connect from a public facing server that is in the same VPC.

If I ssh into that public facing server, I can connect to the redis instance on the private server just fine using redis-cli. But I get I'm getting timeout errors when I try to deploy to production using the following config:

```
'redis': {
  allowOverwrite: true,
  keyPrefix: 'pigeon:index',
  url: 'redis://:' + env('REDIS_PASSWORD') + '@' + env('REDIS_HOST') + ':6379',
},

'ssh-tunnel': {
  username: env('SSH_USER'),
  host: env('SSH_HOST'),
  privateKeyPath: env('SSH_KEY'),
}
```

I'm guessing this is some sort of configuration issue on my end since I don't see any other issues about it. But I get this same error using the host, password, port configuration variation rather than specifying a connection url:

```
Error: Redis connection to internal-pigeon-db-production-1812613668.us-east-1.elb.amazonaws.com:6379 failed - connect ETIMEDOUT 192.168.1.148:6379
    at RedisClient.on_error (/Applications/MAMP/htdocs/pigeon-web-app/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/Applications/MAMP/htdocs/pigeon-web-app/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-redis/node_modules/redis/index.js:106:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Any ideas about what might be causing this?

**Edit:** Explained how I'm using ssh tunnel.

**Comment by ghedamat** [comment]
@BillBrower I see you're using ssh tunnel there?

If that's the case `REDIS_HOST` should be localhost then instead of the remote IP but from the error message it seems that that's not the case?

**Comment by BillBrower** [comment]
That's correct. Redis is running on a server that is not publicly accessible (private subnet) so I'm using ssh tunnel to connect from a public facing server that is in the same VPC.

**Comment by ghedamat** [comment]
right, so can you confim that the value of `REDIS_HOST` is `localhost` ?

this line `Redis connection to internal-pigeon-db-production-1812613668.us-east-1.elb.amazonaws.com:6379 failed - connect ETIMEDOUT 192.168.1.148:6379` seems indicate something different

**Comment by BillBrower** [comment]
Redis isn't on the host I'm connecting to via ssh, it's just accessible from there via `internal-pigeon-db-production-1812613668.us-east-1.elb.amazonaws.com` on port 6379.

**Comment by ghedamat** [comment]
ah sry! I didn't understand the setup :)
ok that makes it clearer. I've never done it but I know that others do what you're doing and use an intermediate jump.

wanna have a chat on slack later today or this week? might be easier to troubleshoot

**Comment by BillBrower** [comment]
Absolutely! Thanks for looking at this. Is there an ember-cli-deploy slack group?

**Comment by ghedamat** [comment]
ember community slack, #ec-deploy channel. or just message me there

**Comment by BillBrower** [comment]
@ghedamat was super kind and walked me through the issue over a screencast. It turns out that my deploy.js was not configured correctly. Here is the working version:

```
/* jshint node: true */
'use strict';

function env(name) {
  if (process.env[name]) {
    return process.env[name];
  } else {
    throw new Error('Expected environment variable `' + name + '` to be set but it was not.');
  }
}

module.exports = function (deployTarget) {
  if (deployTarget === 'development') {
    return {
      'build': { environment: 'development' },
      'plugins': ['build', 'redis', 'display-revisions', 'revision-data'],
      'revision-data': {
        type: 'git-commit'
      },
      'redis': {
        allowOverwrite: true,
        keyPrefix: 'pigeon',
        url: 'redis://127.0.0.1:6379/'
      }
    };
  }

  var ENV = {
    'build': { environment: 'production' },

    'package': require('../package.json'),

    'slack': {
      webhookURL: env('SLACK_WEBHOOK'),
      message: '{git.user.name} deployed {package.name}/{git.branch} to {deploy.target} (took {deploy.duration}s)\n' +
               '{package.repository}/compare/{git.diff}'
    },

    'revision-data': {
      type: 'git-commit'
    },

    'redis': {
      allowOverwrite: true,
      keyPrefix: 'pigeon:index',
      host: '127.0.0.1',
      password: env('REDIS_PASSWORD')
    },

    'ssh-tunnel': {
      username: env('SSH_USER'),
      host: env('SSH_HOST'),
      privateKeyPath: env('SSH_KEY'),
      dstHost: env('REDIS_HOST')
    },

    's3': {
      accessKeyId: env('AWS_KEY'),
      secretAccessKey: env('AWS_SECRET'),
      bucket: env('AWS_BUCKET'),
      region: env('REGION')
    }
  };

  return ENV;
};
```

**Comment by achambers** [comment]
:+1

**Comment by mattboldt** [comment]
Just want to point something out w/ this issue:

When I had the Redis `port` set, it was deploying and listing data from my `localhost` redis server. Once I removed the port, the ssh-tunneling to my EC2 instance started working.

This was quite a head-scratcher until I realized my local redis server was running, which is why I got no errors.

```
    ENV.redis = {
      allowOverwrite: true,
      host: 'localhost',
      port: 6379 // this apparently an important setting
    };
    ENV['ssh-tunnel'] = {
      username: <username>',
      host: <ec2 instance>,
      dstHost: <redis AWS cluster path>,
      privateKeyPath: '/path/to/key'
    };
```

**Comment by achambers** [comment]
@mattboldt It's kind of in the readme, although I'll agree, not all that clear. Fancy submitting a PR with mods that you think would have made it more clear to you?

https://github.com/ember-cli-deploy/ember-cli-deploy-redis/blob/master/README.md#port

**Comment by mattboldt** [comment]
@achambers Pull here: https://github.com/ember-cli-deploy/ember-cli-deploy-redis/pull/70

Not 100% if the option should never be overwritten (even when using ssh-tunneling), so maybe my wording isn't the best.
