### ISSUE TITLE
How do we set the expire for each key?

### ISSUE THREAD

**Issue by tiandavis** [ember-cli-deploy/ember-cli-deploy-redis#69]
Hi Folks,

We're running into a scenario where our Redis store reaches its memory capacity. When that happens, ember deploy fails because there is no room to deploy the index.html to our Redis instance.

We're using RedisToGo, so one approach may be to set our `maxmemory-policy` to `allkeys-lru` since that policy doesn't require keys to have expire set.

```
CONFIG SET maxmemory-policy allkeys-lru
```

Unfortunately, RedisToGo seems to have obfuscated the `CONFIG` command (for security reasons no doubt) and its default `maxmemory-policy` is `volatile-lru` which requires keys to have an expire set in order to make space for any new data added once max memory is met.

Without access to `CONFIG` our only option is to set an expire on our ember cli deployment keys. It doesn't appear that ember-cli-deploy-redis sets an expire by default. Is there a configuration option or some other approach we could take to set an expire during ember cli deploy?

Thanks Everyone!

**Comment by lukemelia** [comment]
@tiandavis: the `maxRecentUploads` config option on this plugin exists for this purpose. Are you able to tune that to get the behavior you need?

**Comment by tiandavis** [comment]
Golly, looking through the source, it looks like it just might! Thanks a bunch @lukemelia!
