### ISSUE TITLE
Difficult Error When URL Missing "redis://"

### ISSUE THREAD

**Issue by jherdman** [ember-cli-deploy/ember-cli-deploy-redis#82]
I'm fairly new to the project, and didn't realize I need to prefix a URL option with "redis://". I know, it's a bonehead move... Any ways... The error you get is:

```
cleaning up...
Deploying [==>------] 33% [plugin: redis -> fetchInitialRevisions]events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

I think we can do a bit better than this. Perhaps checking for this prefix is advisable, or least offering a suggestion to look for this when the failure happens? I'd be more than happy to help if such a solution is desirable.

**Comment by lukemelia** [comment]
I think adding a specific error message here sounds like a great idea. Anything that can save people time. I'd be happy to review a PR for this, @jherdman.
