### ISSUE TITLE
possible to upload multiple files?

### ISSUE THREAD

**Issue by jamemackson** [ember-cli-deploy/ember-cli-deploy-redis#84]
I have run into an issue with compatibility of using the lightning deploy strategy and serving a service worker.  the sw.js file needs to be served up from the root domain and not from a CDN url so I'm wondering if it's possible to deploy both the index.html and sw.js files to redis where I can then adapt my server to also dish out the service worker from the main domain?

so far I've tried updating the filePattern but it feels like this is set to locate 1 file to upload and doesn't support many files... but I'm likely missing something so thought I'd check here.  TIA for the help!

**Comment by achambers** [comment]
Hi @jamemackson

Let's see if we can get you moving again. I'd suggest looking at the section about `alias`ing a plugin, in [the docs](http://ember-cli-deploy.com/docs/v1.0.x/including-a-plugin-twice/)

This should give you everything you need. 

If not, feel free to reopen this issue or hit us up in the #ec-deploy channel in the Ember Communitu Slack.

**Comment by jamemackson** [comment]
Excellent, thanks @achambers!
